name: Check System Info
on:
  pull_request:
    paths:
      - '**'
      - '!**/docs/**'
      - '!docs/**'
      - 'docs/snippets/**'
      - '!**/**.md'
      - '!**.md'

jobs:
  Check:
    timeout-minutes: 5
    defaults:
      run:
        shell: bash
    strategy:
      max-parallel: 3
      fail-fast: false
      matrix:
        machine: [aks-linux-8-cores, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.machine }}

    steps:
      - name: Clone OpenVINO
        uses: actions/checkout@v4
        with:
          path: 'openvino'

      #
      # Print system info
      #

      - name: System info
        uses: ${{ github.workspace }}/openvino/.github/actions/system_info
