name: Gathering Cache Entries
on:
  workflow_dispatch:
#  pull_request:
#  push:
#    branches:
#      - main

jobs:
  Gather_Cache_Entries:
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    env:
      ARTIFACTS_DIR: ${{ github.workspace }}/artifacts
      CONFORMANCE_TOOLS_DIR: ${{ github.workspace }}/install/tests/functional_test_utils/layer_tests_summary
      CONFORMANCE_CACHE_DIR: ${{ github.workspace }}/conformance_cache
      TEST_DEVICE: 'CPU'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Artifacts Directory
        run: mkdir -p ${{ env.ARTIFACTS_DIR }} ${{ env.CONFORMANCE_TOOLS_DIR }} ${{ env.CONFORMANCE_CACHE_DIR }}

      - name: Show Context
        uses: actions/github-script@v6
        with:
          script: |
            console.log(context)
            console.log(context.payload.repository.full_name)
            console.log(context.payload.repository.organization)
            console.log(context.payload.repository.name)

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - run: npm install @actions/cache
      
      - name: Gather Workflows Data
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
                        
            const cache = require('@actions/cache');
            
            function sleep(ms) {
              return new Promise(resolve => setTimeout(resolve, ms));
            }
            
            const org = context.payload.organization.login
            const repositoryName = context.payload.repository.name
            
            const conformanceCacheEntries = await github.rest.actions.getActionsCacheList({
              'owner': org,
              'repo': repositoryName,
              'key': 'Linux-conformance'
            })
            console.log(JSON.stringify(conformanceCacheEntries))
            
            const restorePath = '${{ env.CONFORMANCE_TOOLS_DIR }}/expected_failures_${{ env.TEST_DEVICE }}.csv'
            
            // Download all cache entries
            for (const cacheEntryInfo of conformanceCacheEntries.data.actions_caches) {
              const cacheKey = cacheEntryInfo.key
              const finalPath = `${{ env.CONFORMANCE_TOOLS_DIR }}/${cacheKey}/expected_failures_${{ env.TEST_DEVICE }}.csv`
            
              console.log(`Restoring cache: ${cacheKey}`)
            
              const restoredCacheKey = await cache.restoreCache([restorePath], cacheKey, [])
              
              if (restoredCacheKey) {
            
                // Create dir for the entry
                fs.mkdir(`${{ env.CONFORMANCE_TOOLS_DIR }}/${cacheKey}`, { recursive: true }, (err) => {
                  if (err) throw err;
                });
            
                // Move downloaded cache to its final directory
                fs.rename(restorePath, finalPath, function (err) {
                  if (err) throw err
                  console.log(`${cacheKey} was restored to ${finalPath}.\n`)
                })
              } else {
                console.log(`Cache was not restored: ${cacheKey}.\n`)
              }
              await sleep(4000);
            }

      - name: Check Restoration
        run: ls -laR ${{ env.CONFORMANCE_TOOLS_DIR }}

