name: JS API
on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'src/bindings/js/**'
      - '.github/workflows/js_api.yml'
  push:
    paths:
      - 'src/bindings/js/**'
      - '.github/workflows/js_api.yml'
    branches:
      - master
      - 'releases/**'

concurrency:
  # github.ref is not unique in post-commit
  group: ${{ github.event_name == 'push' && github.run_id || github.ref }}-js-api
  cancel-in-progress: true

jobs:
  JS_API:
    name: Configure and Test JS API Bindings
    strategy:
      max-parallel: 3
      fail-fast: false
      matrix:
        include:
          - machine: 'ubuntu-22.04'
            shell: 'bash'
          - machine: 'windows-2022'
            shell: 'cmd'
          - machine: 'macos-11'
            shell: 'bash'
    defaults:
      run:
        shell: ${{ matrix.shell }}
    runs-on: ${{ matrix.machine }}
    env:
      OPENVINO_REPO: "${{ github.workspace }}/openvino"
      JS_BINDINGS_DIR: "${{ github.workspace }}/openvino/src/bindings/js"
    steps:
      - name: Clone OpenVINO
        uses: actions/checkout@v4
        with:
          path: 'openvino'

      #
      # Dependencies
      #

      - name: Install dependencies (Ubuntu)
        if: ${{ contains(matrix.machine, 'ubuntu') }}
        run: sudo -E ${{ env.OPENVINO_REPO }}/scripts/install_dependencies/install_openvino_dependencies.sh -y

      - name: Install dependencies (mac)
        if: ${{ contains(matrix.machine, 'macos') }}
        run: brew install coreutils

      #
      # Configure JS API
      #

      - name: Configure JS API
        working-directory: ${{ env.JS_BINDINGS_DIR }}/node
        run: npm i

      #
      # Tests
      #

      - name: Run tests (Unix)
        if: ${{ !contains(matrix.machine, 'windows') }}
        working-directory: ${{ env.JS_BINDINGS_DIR }}/node
        run: source ${{ env.JS_BINDINGS_DIR }}/node/ov_runtime/setupvars.sh && npm test

      - name: Run tests (Windows)
        if: ${{ contains(matrix.machine, 'windows') }}
        working-directory: ${{ env.JS_BINDINGS_DIR }}/node
        run: call "${{ env.JS_BINDINGS_DIR }}\\node\\ov_runtime\\setupvars.bat" && npm test
